name: BetterEnderChest
main: nl.rutgerkok.BetterEnderChest.BetterEnderChest
version: 1.0
softdepend: [Lockette, LWC]
commands:
  betterenderchest:
    description: Administrative command for BetterEnderChest.
    aliases: [bec]
    usage: Type /<command> for more information.
permissions:
  betterenderchest.*:
    description: Use all BetterEnderChest features. Only for administrators!
    children:
      betterenderchest.command.*: true
      betterenderchest.use.*: true
  betterenderchest.use:
    description: You can use both private and public Ender Chests. Same as betterenderchest.use.* .
    children:
      betterenderchest.use.*: true
  betterenderchest.use.*:
    description: You can use both private and public Ender Chests. Same as betterenderchest.use .
    children:
      betterenderchest.use.privatechest: true
      betterenderchest.use.publicchest: true
  betterenderchest.use.privatechest:
    description: Use private chests
    default: op
  betterenderchest.use.publicchest:
    description: Use public chests
    default: op
  betterenderchest.rows.upgrade1:
    description: Get the rows as specified for this upgrade in the config.yml.
    default: false
  betterenderchest.rows.upgrade2:
    description: Get the rows as specified for this upgrade in the config.yml.
    default: false
  betterenderchest.command:
    description: Use all commands. Same as betterenderchest.command.* .
    children:
      betterenderchest.command.*: true
  betterenderchest.command.*:
    description: Use all commands. Same as betterenderchest.command .
    default: op
    children:
      betterenderchest.command.deleteinv: true
      betterenderchest.command.give: true
      betterenderchest.command.list: true
      betterenderchest.command.openinv: true
      betterenderchest.command.swapinv: true
  betterenderchest.command.deleteinv:
    description: Delete the contents of an Ender inventory.
  betterenderchest.command.give:
    description: Give an item to an Ender inventory.  
  betterenderchest.command.list:
    description: List all currently loaded Ender inventories.
  betterenderchest.command.openinv:
    description: Open someone's Ender inventory.
  betterenderchest.command.swapinv:
    description: Swap two Ender inventories.