name: BetterEnderChest
main: nl.rutgerkok.BetterEnderChest.BetterEnderChest
version: 0.3
permissions:
    betterenderchest.use:
        description: Use an EnderChest 
softdepend: [Lockette, LWC] 