name: EnderChest
main: nl.rutgerkok.EnderChest.EnderChest
version: 0.1
permissions:
    enderchest.user:
        description: Create an EnderChest, destroy an EnderChest 
softdepend: [Lockette, LWC] 