name: BetterEnderChest
main: nl.rutgerkok.BetterEnderChest.BetterEnderChest
version: 0.4
softdepend: [Lockette, LWC]

permissions:
  betterenderchest.use:
    description: You can use both private and public Ender Chests. Same as betterenderchest.use.* .
    children:
      betterenderchest.use.*: true
  betterenderchest.use.*:
    description: You can use both private and public Ender Chests. Same as betterenderchest.use .
    children:
      betterenderchest.use.privatechest: true
      betterenderchest.use.publicchest: true
  betterenderchest.use.privatechest:
    description: Use private chests
    default: op
  betterenderchest.use.publicchest:
    description: Use public chests
    default: op